FROM alpine

RUN echo "MESSAGE_GO_HERE" > image_salt_1

RUN echo "MESSAGE_GO_HERE" > image_salt_2

RUN echo "MESSAGE_GO_HERE" > image_salt_3

RUN echo "MESSAGE_GO_HERE" > image_salt_4

RUN echo "MESSAGE_GO_HERE" > image_salt_5